# Generated by Django 3.1.5 on 2021-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(verbose_name='основной текст сообщения в правом садбаре')),
                ('text', models.TextField(verbose_name='сообщение ниже главного текста кврсиавом')),
            ],
            options={
                'verbose_name': 'cooбщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
