# Generated by Django 3.1.5 on 2021-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210115_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
